<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class AiContentService
{
    public function generateDraft(string $title): string
    {
        $prompt     = $this->buildPrompt($title);

        $response   = $this->makeGeminiRequest($prompt);

        $content    = $this->extractContentFromResponse($response);

        return $content;
    }

    private function buildPrompt(string $title): string
    {
        return "Create a Magic: The Gathering Commander legal format deck based on {$title}.
        Requirements:
        - The deck has to contain exactly 100 cards, including the commander.
        - Include 1 legendary creature as the commander unless the user asks for a different commander configuration.
        - Follow Magic: The Gathering commander color identity rules, so no cards that go against the given commander's color identity.
        - Do not include cards banned in Commander format.
        - Only use real Magic: The Gathering cards, so do not invent card names, abilities, mana costs, types, or other card information.
        - Ensure all cards listed work well with the requested commander or deck strategy.
        - Ensure there's an appropriate balance of each card type with at least 30 lands.
        - Write a description before the decklist explaining the strategy of the deck.
        - Ensure the decklist is organized according to card type and that each card is placed in the correct category:
        commander, creatures, lands, sorceries, instants, enchantments, artifacts, and planeswalkers.
        - Ensure the decklist is well-organized and easy to follow.
        - Ensure the entire content is work-appropriate.
        - If you are uncertain about a card, use a different card.";
    }

    private function makeGeminiRequest(string $prompt): array
    {
        try {
            $response = Http::withHeaders([
                'x-goog-api-key' => config('services.gemini.key'),
                'Content-Type'   => 'application/json',
            ])->post(config('services.gemini.url') . '/models/' . config('services.gemini.model') . ':generateContent',
            [
                'systemInstruction' => [
                    'parts' => [['text' => 'You are a meticulous Magic: The Gathering deck-building assistant.']],
                ],
                'contents' => [
                    ['parts' => [['text' => $prompt]]],
                ],
                'generationConfig' => [
                'temperature'      => 0.2,
                'maxOutputTokens'  => 5000,
                ],
            ]);

            if (! $response->successful()) {
                Log::error('Gemini request failed', [
                    'status' => $response->status(),
                    'body'   => $response->body(),
                ]);

                throw new \Exception('The API request failed: ' . $response->body());
            }

            return $response->json();

        } catch (\Throwable $e) {
            Log::error('Gemini communication failed', [
                'error' => $e->getMessage(),
                'prompt_length' => strlen($prompt),
            ]);

            throw new \Exception('Failed to communicate with AI service: ' . $e->getMessage());
        }
    }

    private function extractContentFromResponse(array $response): string
    {
        if (!isset($response['candidates'][0]['content']['parts'][0]['text'])) {
            throw new \Exception('Unexpected response format from Gemini API');
        }

        $content = trim($response['candidates'][0]['content']['parts'][0]['text']);

        if (empty($content)) {
            throw new \Exception('No content generated by AI service');
        }

        return $content;
    }
}