<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class AiContentService
{
    public function generateDraft(string $title): string
    {
        $prompt     = $this->buildPrompt($title);

        $response   = $this->makeGeminiRequest($prompt);

        $content    = $this->extractContentFromResponse($response);

        return $content;
    }

    private function buildPrompt(string $title): string
    {
        return "Create a Magic: The Gathering Commander legal format deck based on {$title}.
        Write a description at the top of the deck based on the user's tone.
        Make sure the content is cohesive, easy to follow, and work-appropriate.";
    }

    private function makeGeminiRequest(string $prompt): array
    {
        try {
            $response = Http::withHeaders([
                'x-goog-api-key' => config('services.gemini.key'),
                'Content-Type'   => 'application/json',
            ])->post(config('services.gemini.url') . '/models/' . config('services.gemini.model') . ':generateContent',
            [
                'systemInstruction' => [
                    'parts' => [['text' => 'You are a friendly and fun writing assistant.']],
                ],
                'contents' => [
                    ['parts' => [['text' => $prompt]]],
                ],
                'generationConfig' => [
                'temperature'      => 0.7,
                'maxOutputTokens'  => 2000,
                ],
            ]);

            if (! $response->successful()) {
                Log::error('Gemini request failed', [
                    'status' => $response->status(),
                    'body'   => $response->body(),
                ]);

                throw new \Exception('The API request failed: ' . $response->body());
            }

            return $response->json();

        } catch (\Throwable $e) {
            Log::error('Gemini communication failed', [
                'error' => $e->getMessage(),
                'prompt_length' => strlen($prompt),
            ]);

            throw new \Exception('Failed to communicate with AI service: ' . $e->getMessage());
        }
    }

    private function extractContentFromResponse(array $response): string
    {
        if (!isset($response['candidates'][0]['content']['parts'][0]['text'])) {
            throw new \Exception('Unexpected response format from Gemini API');
        }

        $content = trim($response['candidates'][0]['content']['parts'][0]['text']);

        if (empty($content)) {
            throw new \Exception('No content generated by AI service');
        }

        return $content;
    }
}